theme: jekyll-theme-cayman
title: 中国节能与新能源汽车产业数据库
description: Data Base of Hybrid and Electric Vehicle Production in China 引用请注明：王贺武. 中国节能与新能源汽车产业数据库，清华大学汽车安全与节能国家重点实验室,wanghw@tsinghua.edu.cn
# 中国新能源汽车产量（截止2019年12月）
[Link](url) and ![Image](src)
